# Generated by Django 4.2.3 on 2023-07-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_text', models.TextField(verbose_name='public_text')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('model_product', models.CharField(max_length=128)),
                ('auction', models.BooleanField(help_text='Yes and not', verbose_name='Torg')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
