# Generated by Django 4.2.3 on 2023-07-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_work_5', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
