# Generated by Django 4.2.3 on 2023-07-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_work_5', '0003_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
