# Generated by Django 4.2.3 on 2023-07-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_work_5', '0004_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table=None,
        ),
    ]
