# Generated by Django 4.2.3 on 2023-07-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_work_5', '0006_advertisement_2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement_2',
            table='advertisements',
        ),
    ]
