# Generated by Django 4.2.3 on 2023-07-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_work_5', '0010_alter_advertisement_2_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement_2',
            table='advertisements',
        ),
    ]
