# Generated by Django 4.2.3 on 2023-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_work_5', '0011_alter_advertisement_2_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement_2',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновленно'),
        ),
    ]
